// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// bmat_schC
NumericMatrix bmat_schC(double v1, double v2, double v3, NumericVector section_counts);
RcppExport SEXP rlme_bmat_schC(SEXP v1SEXP, SEXP v2SEXP, SEXP v3SEXP, SEXP section_countsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< double >::type v1(v1SEXP );
        Rcpp::traits::input_parameter< double >::type v2(v2SEXP );
        Rcpp::traits::input_parameter< double >::type v3(v3SEXP );
        Rcpp::traits::input_parameter< NumericVector >::type section_counts(section_countsSEXP );
        NumericMatrix __result = bmat_schC(v1, v2, v3, section_counts);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// bmat2C
NumericVector bmat2C(double v1, double v2, NumericVector sec);
RcppExport SEXP rlme_bmat2C(SEXP v1SEXP, SEXP v2SEXP, SEXP secSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< double >::type v1(v1SEXP );
        Rcpp::traits::input_parameter< double >::type v2(v2SEXP );
        Rcpp::traits::input_parameter< NumericVector >::type sec(secSEXP );
        NumericVector __result = bmat2C(v1, v2, sec);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// pairup
NumericMatrix pairup(NumericVector vec, String type = "less");
RcppExport SEXP rlme_pairup(SEXP vecSEXP, SEXP typeSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type vec(vecSEXP );
        Rcpp::traits::input_parameter< String >::type type(typeSEXP );
        NumericMatrix __result = pairup(vec, type);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// remove_k_smallest
NumericVector remove_k_smallest(NumericVector v, int k);
RcppExport SEXP rlme_remove_k_smallest(SEXP vSEXP, SEXP kSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type v(vSEXP );
        Rcpp::traits::input_parameter< int >::type k(kSEXP );
        NumericVector __result = remove_k_smallest(v, k);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// rhoschC
List rhoschC(NumericVector ahat, NumericVector section_counts, NumericMatrix student_counts);
RcppExport SEXP rlme_rhoschC(SEXP ahatSEXP, SEXP section_countsSEXP, SEXP student_countsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type ahat(ahatSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type section_counts(section_countsSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type student_counts(student_countsSEXP );
        List __result = rhoschC(ahat, section_counts, student_counts);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
// rhosectC
List rhosectC(NumericVector ahat, NumericVector section_counts, NumericMatrix student_counts);
RcppExport SEXP rlme_rhosectC(SEXP ahatSEXP, SEXP section_countsSEXP, SEXP student_countsSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericVector >::type ahat(ahatSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type section_counts(section_countsSEXP );
        Rcpp::traits::input_parameter< NumericMatrix >::type student_counts(student_countsSEXP );
        List __result = rhosectC(ahat, section_counts, student_counts);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
