# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bmat_schC <- function(v1, v2, v3, section_counts) {
    .Call('rlme_bmat_schC', PACKAGE = 'rlme', v1, v2, v3, section_counts)
}

bmat2C <- function(v1, v2, sec) {
    .Call('rlme_bmat2C', PACKAGE = 'rlme', v1, v2, sec)
}

pairup <- function(vec, type = "less") {
    .Call('rlme_pairup', PACKAGE = 'rlme', vec, type)
}

remove_k_smallest <- function(v, k) {
    .Call('rlme_remove_k_smallest', PACKAGE = 'rlme', v, k)
}

rhoschC <- function(ahat, section_counts, student_counts) {
    .Call('rlme_rhoschC', PACKAGE = 'rlme', ahat, section_counts, student_counts)
}

rhosectC <- function(ahat, section_counts, student_counts) {
    .Call('rlme_rhosectC', PACKAGE = 'rlme', ahat, section_counts, student_counts)
}

